<?php

$root = dirname(__DIR__);

function phase1_assert_contains($contents, $needle, $message)
{
    if (strpos($contents, $needle) === false) {
        fwrite(STDERR, "FAIL: {$message}\n");
        exit(1);
    }
}

function phase1_assert_not_contains($contents, $needle, $message)
{
    if (strpos($contents, $needle) !== false) {
        fwrite(STDERR, "FAIL: {$message}\n");
        exit(1);
    }
}

$bookingView = file_get_contents($root . '/application/views/users/book_space.php');
$bookingJs = file_get_contents($root . '/assets/users/js/booking.js');
$bookingCss = file_get_contents($root . '/assets/users/css/custom.css');
$historyView = file_get_contents($root . '/application/views/users/history.php');
$successView = file_get_contents($root . '/application/views/users/booking_success.php');
$emailView = file_get_contents($root . '/application/views/mail/user_booking_notification_email.php');
$helper = file_get_contents($root . '/application/helpers/app_helper.php');
$controller = file_get_contents($root . '/application/controllers/User_bookings.php');
$usersModel = file_get_contents($root . '/application/models/Users_model.php');
$userBookingsModel = file_get_contents($root . '/application/models/User_bookings_model.php');
$bookingsModel = file_get_contents($root . '/application/models/Bookings_model.php');

phase1_assert_contains($bookingView, 'id="parcel-guarantee-notice"', 'Parcel Guarantee should have a dedicated conditional notice.');
phase1_assert_contains($bookingView, 'data-coverage="100"', 'The lower guarantee should map to 100 coverage.');
phase1_assert_contains($bookingView, 'data-coverage="300"', 'The higher guarantee should map to 300 coverage.');
phase1_assert_contains($bookingView, 'Parcel Protection⁺', 'The Plus option should use a superscript plus.');
phase1_assert_contains($bookingView, 'data-protection-label="Parcel Protection"', 'The standard option should define its notice label.');
phase1_assert_contains($bookingView, 'data-protection-label="Parcel Protection Plus"', 'The Plus option should define its notice label.');
phase1_assert_contains($bookingView, 'id="parcel-protection-name"', 'The notice should expose a dynamic protection name.');
phase1_assert_contains($bookingView, 'id="parcel-guarantee-price"', 'The notice should show the selected guarantee price.');
phase1_assert_contains($bookingView, 'aria-live="polite"', 'The conditional guarantee notice should announce changes accessibly.');
phase1_assert_contains($bookingJs, 'updateParcelGuaranteeNotice', 'Booking JavaScript should update the selected guarantee notice.');
phase1_assert_contains($bookingJs, 'protectionNameTarget.text(protectionName)', 'Booking JavaScript should update the selected protection name.');
phase1_assert_contains($bookingCss, '.parcel-guarantee-notice', 'The guarantee notice should have prominent scoped styling.');

phase1_assert_not_contains($bookingView, 'name="need_help"', 'The legacy Need Help booking checkbox should be removed.');
phase1_assert_not_contains($controller, "set_rules('need_help'", 'New booking validation should no longer accept the legacy Need Help field.');
phase1_assert_not_contains($usersModel, "'need_help'       => \$this->input->post('need_help'", 'The active booking model should no longer persist customer-submitted Need Help values.');
phase1_assert_not_contains($userBookingsModel, "'need_help'       => \$this->input->post('need_help'", 'The legacy user booking model should no longer persist customer-submitted Need Help values.');
phase1_assert_not_contains($bookingsModel, "'need_help'       => \$this->input->post('need_help'", 'The booking model should no longer persist customer-submitted Need Help values.');

phase1_assert_contains($helper, 'function booking_support_whatsapp_url', 'WhatsApp support URLs should be generated by a shared helper.');
phase1_assert_contains($helper, 'Booking reference:', 'The support message should include the booking reference.');
phase1_assert_contains($helper, 'Customer:', 'The support message should include the customer name.');
phase1_assert_contains($helper, 'Traveller:', 'The support message should include the traveller name.');
phase1_assert_contains($helper, 'Route:', 'The support message should include the booking route.');
phase1_assert_contains($helper, 'Amount:', 'The support message should include the booking amount.');

phase1_assert_contains($historyView, 'Need help with this parcel?', 'Completed booking history should expose the WhatsApp support link.');
phase1_assert_contains($successView, 'Need help with this parcel?', 'The booking success page should expose the WhatsApp support link.');
phase1_assert_contains($emailView, 'Need help with this parcel?', 'The booking confirmation email should expose the WhatsApp support link.');
phase1_assert_contains($controller, "set_flashdata('booking_success_id'", 'The success redirect should retain the completed booking context.');
phase1_assert_contains($controller, '(int) $booking->user_id === (int) $this->user_details->id', 'Success-page booking context should be ownership checked.');

fwrite(STDOUT, "PASS: Phase 1 Parcel Guarantee and booking support contracts are present.\n");
